name: Auto Commit via Pull Request

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "your-username"
          git config user.email "your-email@example.com"

      - name: Create/update commit
        run: |
          git checkout -B auto-update

          # Generate data
          EMOJIS=("🎯" "💪" "📅" "🚀" "✅")
          QUOTES=(
            "Push yourself, because no one else is going to do it for you."
            "Stay positive, work hard, make it happen."
            "Dream it. Wish it. Do it."
            "Don’t stop when you’re tired. Stop when you’re done."
          )

          EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          COUNT=$(grep -c "^" commit_log.txt 2>/dev/null || echo 0)
          COUNT=$((COUNT + 1))
          echo "${COUNT}. ${EMOJI} Commit on $(date): ${QUOTE}" >> commit_log.txt

          git add commit_log.txt
          git commit -m "chore: ${EMOJI} Auto commit #${COUNT}" || echo "No changes to commit"

      - name: Push to branch
        run: git push -f origin auto-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR: Update commit log"
          title: "🤖 Auto PR: Daily Update #${{ github.run_number }}"
          body: "This PR was automatically generated."
          branch: auto-update
          base: main
