name: Auto Commit to Main Branch

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 7:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "goutham-shankar"
          git config --global user.email "gouthamsankarv@gmail.com"

      - name: Create or update commit_log.txt
        run: |
          EMOJIS=("🎯" "🔥" "💪" "📅" "🧠" "🚀" "💻" "✅")
          QUOTES=(
            "Push yourself, because no one else is going to do it for you."
            "Stay positive, work hard, make it happen."
            "Dream it. Wish it. Do it."
            "Don’t stop when you’re tired. Stop when you’re done."
            "Success doesn’t just find you. You have to go out and get it."
            "Great things never come from comfort zones."
          )

          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          COUNT=$(grep -c "^" commit_log.txt 2>/dev/null || echo 0)
          COUNT=$((COUNT + 1))

          echo "${COUNT}. ${RANDOM_EMOJI} Commit on $(date): ${RANDOM_QUOTE}" >> commit_log.txt

          git add commit_log.txt
          git commit -m "chore: ${RANDOM_EMOJI} Auto commit #${COUNT}" || echo "No changes to commit"

      - name: Push changes to main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git main
