name: Daily Contribution Commit

on:
  schedule:
    - cron: '0 7 * * *' # Every day at 7 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate daily commit
        run: |
          # Random emoji
          EMOJIS=("🎯" "🔥" "💪" "📅" "🧠" "🚀" "💻" "✅")
          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}

          # Pick a random quote
          QUOTES=(
            "Push yourself, because no one else is going to do it for you."
            "Stay positive, work hard, make it happen."
            "Dream it. Wish it. Do it."
            "Don’t stop when you’re tired. Stop when you’re done."
            "Success doesn’t just find you. You have to go out and get it."
            "Great things never come from comfort zones."
          )
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          # Count previous commits
          COUNT=$(grep -c "^" commit_log.txt 2>/dev/null || echo 0)
          COUNT=$((COUNT + 1))

          # Append to file
          echo "${COUNT}. ${RANDOM_EMOJI} Commit on $(date): ${RANDOM_QUOTE}" >> commit_log.txt

          # Configure Git
          git config --global user.name "goutham-shankar"
          git config --global user.email "gouthamsankarv@gmail.com"

          git add commit_log.txt
          git commit -m "chore: ${RANDOM_EMOJI} Auto commit #${COUNT}"
          git push
