name: Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for checkout

      - name: Setup Git
        run: |
          git config user.name "goutham-shankar"
          git config user.email "gouthamsankarv@gmail.com"

      - name: Create or update commit_log.txt
        run: |
          EMOJIS=("🎯" "🔥" "💪" "📅" "🧠" "🚀" "💻" "✅")
          QUOTES=(
            "Push yourself, because no one else is going to do it for you."
            "Stay positive, work hard, make it happen."
            "Dream it. Wish it. Do it."
            "Don't stop when you're tired. Stop when you're done."
            "Success doesn't just find you. You have to go out and get it."
            "Great things never come from comfort zones."
          )

          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          COUNT=$(grep -c "^" commit_log.txt 2>/dev/null || echo 0)
          COUNT=$((COUNT + 1))

          echo "${COUNT}. ${RANDOM_EMOJI} Commit on $(date): ${RANDOM_QUOTE}" >> commit_log.txt
          
          # Commit and push directly
          git add commit_log.txt
          git commit -m "chore: ${RANDOM_EMOJI} Auto commit #${COUNT}" || echo "No changes to commit"
          git push origin main
