name: Auto Commit via Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  auto-commit-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false  # disable default token to use PAT explicitly

      - name: Setup Git
        run: |
          git config user.name "goutham-shankar"
          git config user.email "gouthamsankarv@gmail.com"

      - name: Create or update commit_log.txt
        run: |
          EMOJIS=("🎯" "🔥" "💪" "📅" "🧠" "🚀" "💻" "✅")
          QUOTES=(
            "Push yourself, because no one else is going to do it for you."
            "Stay positive, work hard, make it happen."
            "Dream it. Wish it. Do it."
            "Don’t stop when you’re tired. Stop when you’re done."
            "Success doesn’t just find you. You have to go out and get it."
            "Great things never come from comfort zones."
          )

          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          COUNT=$(grep -c "^" commit_log.txt 2>/dev/null || echo 0)
          COUNT=$((COUNT + 1))

          echo "${COUNT}. ${RANDOM_EMOJI} Commit on $(date): ${RANDOM_QUOTE}" >> commit_log.txt

          git checkout -B auto-update
          git add commit_log.txt
          git commit -m "chore: ${RANDOM_EMOJI} Auto commit #${COUNT}" || echo "No changes to commit"

      - name: Show git status and branches
        run: |
          git status
          git branch -vv

      - name: Push branch to GitHub
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin auto-update
          git reset --hard origin/auto-update
          git push --force-with-lease https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git auto-update

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Auto PR: Update commit log"
          title: "🤖 Auto PR: Daily Update #${{ github.run_number }}"
          body: "This PR was automatically generated by the auto commit workflow."
          branch: auto-update
          base: main
