name: Simple Auto Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '25 3 * * *'  # runs daily at 3:25 UTC (8:55 AM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "goutham-shankar"
          git config user.email "gouthamsankarv@gmail.com"

      - name: Create or update commit file
        run: |
          # Get the current date and time
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          
          # Create/update the commit file
          echo "Auto commit: $TIMESTAMP" >> auto-commit-log.txt
          
          # Add the file to git
          git add auto-commit-log.txt
          
          # Commit and push
          git commit -m "Auto commit: $TIMESTAMP" || echo "No changes to commit"
          git push origin main
